export const CODE_TO_COUNTRY: Record<string, string> = {
  AF:"afghanistan", AL:"albania", DZ:"algeria", AD:"andorra", AO:"angola", AG:"antigua-and-barbuda", AR:"argentina", AM:"armenia",
  AU:"australia", AT:"austria", AZ:"azerbaijan", BS:"bahamas", BH:"bahrain", BD:"bangladesh", BB:"barbados", BY:"belarus",
  BE:"belgium", BZ:"belize", BJ:"benin", BT:"bhutan", BO:"bolivia", BA:"bosnia-and-herzegovina", BW:"botswana", BR:"brazil",
  BN:"brunei", BG:"bulgaria", BF:"burkina-faso", BI:"burundi", KH:"cambodia", CM:"cameroon", CA:"canada", CV:"cape-verde",
  CF:"central-african-republic", TD:"chad", CL:"chile", CN:"china", CO:"colombia", KM:"comoros", CG:"congo", CD:"democratic-republic-of-the-congo",
  CR:"costa-rica", CI:"ivory-coast", HR:"croatia", HK:"hong-kong", CU:"cuba", CY:"cyprus", CZ:"czech-republic", DK:"denmark",
  DJ:"djibouti", DM:"dominica", DO:"dominican-republic", EC:"ecuador", EG:"egypt", SV:"el-salvador", GQ:"equatorial-guinea", ER:"eritrea",
  EE:"estonia", SZ:"eswatini", ET:"ethiopia", FJ:"fiji", FI:"finland", FR:"france", GA:"gabon", GM:"gambia",
  GE:"georgia", DE:"germany", GH:"ghana", GR:"greece", GD:"grenada", GT:"guatemala", GN:"guinea", GW:"guinea-bissau",
  GY:"guyana", HT:"haiti", HN:"honduras", HU:"hungary", IS:"iceland", IN:"india", ID:"indonesia", IR:"iran",
  IQ:"iraq", IE:"ireland", IL:"israel", IT:"italy", JM:"jamaica", JP:"japan", JO:"jordan", KZ:"kazakhstan",
  KE:"kenya", KI:"kiribati", KP:"north-korea", KR:"south-korea", KW:"kuwait", KG:"kyrgyzstan", LA:"laos", LV:"latvia",
  LB:"lebanon", LS:"lesotho", LR:"liberia", LY:"libya", LI:"liechtenstein", LT:"lithuania", LU:"luxembourg", MG:"madagascar",
  MW:"malawi", MY:"malaysia", MV:"maldives", ML:"mali", MT:"malta", MH:"marshall-islands", MR:"mauritania", MU:"mauritius",
  MX:"mexico", FM:"micronesia", MD:"moldova", MC:"monaco", MN:"mongolia", ME:"montenegro", MA:"morocco", MZ:"mozambique",
  MM:"myanmar", NA:"namibia", NR:"nauru", NP:"nepal", NL:"netherlands", NZ:"new-zealand", NI:"nicaragua", NE:"niger",
  NG:"nigeria", NO:"norway", OM:"oman", PK:"pakistan", PW:"palau", PA:"panama", PG:"papua-new-guinea", PY:"paraguay",
  PE:"peru", PH:"philippines", PL:"poland", PT:"portugal", QA:"qatar", RO:"romania", RU:"russia", RW:"rwanda",
  KN:"saint-kitts-and-nevis", LC:"saint-lucia", VC:"saint-vincent-and-the-grenadines", WS:"samoa", SM:"san-marino", ST:"sao-tome-and-principe", SA:"saudi-arabia", SN:"senegal",
  RS:"serbia", SC:"seychelles", SL:"sierra-leone", SG:"singapore", SK:"slovakia", SI:"slovenia", SB:"solomon-islands", SO:"somalia",
  ZA:"south-africa", ES:"spain", LK:"sri-lanka", SD:"sudan", SS:"south-sudan", SR:"suriname", SE:"sweden", CH:"switzerland",
  SY:"syria", TW:"taiwan", TJ:"tajikistan", TZ:"tanzania", TH:"thailand", TL:"timor-leste", TG:"togo", TO:"tonga",
  TT:"trinidad-and-tobago", TN:"tunisia", TR:"turkey", TM:"turkmenistan", TV:"tuvalu", UG:"uganda", UA:"ukraine", AE:"united-arab-emirates",
  GB:"united-kingdom", US:"united-states", UY:"uruguay", UZ:"uzbekistan", VU:"vanuatu", VA:"vatican-city", VE:"venezuela", VN:"vietnam",
  YE:"yemen", ZM:"zambia", ZW:"zimbabwe"
};